version: '3.8'

volumes:
  postgres-data:

services:
  app:
    image: "mcr.microsoft.com/devcontainers/rust"
    command: sleep infinity

    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - "SYS_PTRACE"

    volumes:
      - "../..:/workspaces:cached"
    env_file: ".env"

  db:
    image: "redis"
    restart: unless-stopped
